name: CI

on:
  push:
    branches: ["trunk"]
    tags: ["*"]

env:
  GITHUB_TOKEN: ${{ secrets.ZZSPEC_PUBLISH_TOKEN }}
          
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: tests
        run: sbt "test"
      - name: publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: sbt "publish" || true

