name: CI run
on:
  push:
    branches:
      - 'trunk'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: tests
        run: sbt +test
