name: CI

on:
  push:
    branches: ["trunk"]
    tags: ["*"]

concurrency: 
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true


# env:
#   GITHUB_TOKEN: ${{ secrets.ZZSPEC_PUBLISH_TOKEN }}
          
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: tests
        run: sbt "test"
      # - name: publish
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: sbt "publish" || true
      # - name: publish docs
      #   run: sbt "ghpagesPushSite" || true 

