name: "on pull request - byggsteg"

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  on-pull-request-byggsteg:
    runs-on: ubuntu-latest
    steps:
      - name: "trigger build and test at byggsteg"
        run: |
           curl 'https://byggsteg.jointhefreeworld.org/api/jobs/submit' \
               -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
               -H 'Authorization: Basic ${{secrets.BYGGSTEG_KEY}}' \
               --data-urlencode "job-code=\`((project . \"zzspec\")(branch-name . \"${{ github.head_ref || github.ref_name }}\")(task . \"pull-and-restart\")(clone-url . \"https://github.com/jjba23/zzspec\"))"
